INFO <WSGIRequest: GET '/'> request received
WARNING Not Found: /favicon.ico
INFO C:\Users\mike\PycharmProjects\dj-seminars\main\views.py changed, reloading.
INFO <WSGIRequest: GET '/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /seminar1
INFO <WSGIRequest: GET '/seminar2/'> request received
INFO <WSGIRequest: GET '/seminar2/dice/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /favicon.ico
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 24, in heads_tails
    return HttpResponse(res_w.statistic(res_w))
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    res_dict.setdefault(self.all())
AttributeError: 'HeadsTails' object has no attribute 'all'
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 24, in heads_tails
    return HttpResponse(res_w.statistic(res_w))
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    res_dict.setdefault(self.all())
AttributeError: 'HeadsTails' object has no attribute 'all'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/'> request received
WARNING Not Found: /heads_tails
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    return HttpResponse(res_w.statistic(n))
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 13, in statistic
    return str(HeadsTails.res_dict[:n])
TypeError: unhashable type: 'slice'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/'> request received
INFO <WSGIRequest: GET '/seminar2/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /favicon.ico
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 28, in heads_tails
    print(data[0])
TypeError: 'DeferredAttribute' object is not subscriptable
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 29, in heads_tails
    return HttpResponse(data[0])
TypeError: 'DeferredAttribute' object is not subscriptable
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    dict_res = {n: query[n] for n in query}
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in <dictcomp>
    dict_res = {n: query[n] for n in query}
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\query.py", line 418, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not HeadsTails.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 28, in heads_tails
    print(data)
NameError: name 'data' is not defined
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 27, in heads_tails
    return HttpResponse(**data)
TypeError: keywords must be strings
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 27, in heads_tails
    return HttpResponse(*data)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\http\response.py", line 374, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\http\response.py", line 139, in __init__
    raise ValueError("HTTP status code must be an integer from 100 to 599.")
ValueError: HTTP status code must be an integer from 100 to 599.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 10, in statistic
    query = (HeadsTails.objects.all())[:-5]
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    query = query.reverse()[:5]
TypeError: 'NoneType' object is not subscriptable
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 15, in statistic
    dict_res = {n: query[n] for n in range(len(query))}
TypeError: object of type 'NoneType' has no len()
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 14, in statistic
    query = query.sort()[:5]
TypeError: '<' not supported between instances of 'HeadsTails' and 'HeadsTails'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 14, in statistic
    query = query.sort()[:5]
AttributeError: 'QuerySet' object has no attribute 'sort'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 14, in statistic
    query = query[:-5]
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 14, in statistic
    list_res = query.reverse()[:5]
TypeError: 'NoneType' object is not subscriptable
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    list_res = query.reverse()[:5]
TypeError: 'NoneType' object is not subscriptable
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic()
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    list_res = query.reverse()[:5]
TypeError: 'NoneType' object is not subscriptable
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic(n)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py", line 11, in statistic
    list_res = query[-n:]
TypeError: bad operand type for unary -: 'str'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /seminar2/heads_tails/10
WARNING Not Found: /seminar2/heads_tails/n=10
INFO <WSGIRequest: GET '/seminar2/heads_tails/?n=10'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/?n=20'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/?n=1'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\models.py changed, reloading.
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\urls.py changed, reloading.
INFO <WSGIRequest: GET '/'> request received
WARNING Not Found: /articles
INFO <WSGIRequest: GET '/seminar2/articles/'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\urls.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/'> request received
INFO <WSGIRequest: GET '/seminar2/comments/'> request received
ERROR Internal Server Error: /seminar2/comments/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 44, in comment_read
    comment_id = request.get('comment_id')
AttributeError: 'WSGIRequest' object has no attribute 'get'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/comments/'> request received
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
WARNING Not Found: /seminar2/comments/comment_create/
INFO <WSGIRequest: GET '/seminar2/comments/create/?author_id=1&article_id=1'> request received
ERROR Internal Server Error: /seminar2/comments/create/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 50, in comment_create
    author_id = request.get('author_id')
AttributeError: 'WSGIRequest' object has no attribute 'get'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/comments/create/?author_id=1&article_id=1'> request received
ERROR Internal Server Error: /seminar2/comments/create/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 50, in comment_create
    author_id = request.get['author_id']
AttributeError: 'WSGIRequest' object has no attribute 'get'
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/comments/create/?author_id=1&article_id=1'> request received
ERROR Internal Server Error: /seminar2/comments/create/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: seminar2_comment.article_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 59, in comment_create
    comment.save()
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: seminar2_comment.article_id
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/comments/create/?author_id=1&article_id=1'> request received
ERROR Internal Server Error: /seminar2/comments/create/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 50, in comment_create
    author_id = request.GET.get['author_id']
TypeError: 'method' object is not subscriptable
INFO C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/comments/create/?author_id=1&article_id=1'> request received
ERROR Internal Server Error: /seminar2/comments/create/
Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: seminar2_comment.article_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\seminar2\views.py", line 59, in comment_create
    comment.save()
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mike\PycharmProjects\dj-seminars\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: seminar2_comment.article_id
INFO <WSGIRequest: GET '/seminar2/comments/create/?author_id=1&article_id=1'> request received
INFO <WSGIRequest: GET '/seminar2/comments/'> request received
INFO <WSGIRequest: GET '/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 26, in heads_tails
    print(data.values())
AttributeError: 'list' object has no attribute 'values'
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO E:\git\python\dj_test\seminar2\models.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\models.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\models.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic(n)
  File "E:\git\python\dj_test\seminar2\models.py", line 18, in statistic
    if "Орел" in item[1]:
TypeError: 'HeadsTails' object is not subscriptable
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic(n)
  File "E:\git\python\dj_test\seminar2\models.py", line 18, in statistic
    if "Орел" in item:
TypeError: argument of type 'HeadsTails' is not iterable
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
ERROR Internal Server Error: /seminar2/heads_tails/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 25, in heads_tails
    data = HeadsTails.statistic(n)
  File "E:\git\python\dj_test\seminar2\models.py", line 18, in statistic
    if "Орел" in item:
TypeError: argument of type 'HeadsTails' is not iterable
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO E:\git\python\dj_test\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/?n=10'> request received
WARNING Not Found: /seminar1/heads_tails
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/?n=10'> request received
INFO <WSGIRequest: GET '/seminar2/authors/'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/?author_id=1'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/?author_id=1'> request received
INFO <WSGIRequest: GET '/seminar2/articles/?author_id=1'> request received
INFO E:\git\python\dj_test\seminar2\urls.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/create/?author_id=1'> request received
INFO <WSGIRequest: GET '/seminar2/articles/create/?author_id=1'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
ERROR Internal Server Error: /seminar2/articles/update/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 60, in article_update
    author = Article.objects.filter(article_id=article_id).first()
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'article_id' into field. Choices are: author, author_id, category, comment, content, id, is_published, published, show_count, title
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
ERROR Internal Server Error: /seminar2/articles/update/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 60, in article_update
    author_id = Article.objects.filter(article_id=article_id).first().id
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'article_id' into field. Choices are: author, author_id, category, comment, content, id, is_published, published, show_count, title
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
ERROR Internal Server Error: /seminar2/articles/update/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: seminar2_article.author_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 69, in article_update
    article.save()
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: seminar2_article.author_id
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
ERROR Internal Server Error: /seminar2/articles/update/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view seminar2.views.article_update didn't return an HttpResponse object. It returned None instead.
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
ERROR Internal Server Error: /seminar2/articles/update/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 61, in article_update
    article.author = Article.objects.filter(id=article_id).first().author_id
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "1": "Article.author" must be a "Author" instance.
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/delete/?article_id=3'> request received
ERROR Internal Server Error: /seminar2/articles/delete/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 72, in article_delete
    article.delete()
AttributeError: 'NoneType' object has no attribute 'delete'
INFO <WSGIRequest: GET '/seminar2/articles/delete/?article_id=4'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\urls.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/article_by_author/?name=mike'> request received
ERROR Internal Server Error: /seminar2/articles/article_by_author/
Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\dj_test\seminar2\views.py", line 46, in article_by_author
    article = Article.objects.filter(id=author_id).all()
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\git\python\dj_test\venv\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Author:   first name: mike, last name: unname  >.
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/article_by_author/?name=mike'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/article_by_author/?name=mike'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/articles/article_by_author/?name=mike'> request received
INFO E:\git\python\dj_test\seminar2\views.py changed, reloading.
INFO E:\git\python\dj_test\seminar2\urls.py changed, reloading.
WARNING Not Found: /seminar2/articles/comment_by_article/
WARNING Not Found: /seminar2/articles/comment_by_article/
INFO <WSGIRequest: GET '/seminar2/comments/comment_by_article/?name=new_article'> request received
INFO <WSGIRequest: GET '/seminar2/articles/update/?article_id=2'> request received
INFO E:\git\python\django_seminars\seminar1\views.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO "GET / HTTP/1.1" 200 10
INFO "GET /seminar2 HTTP/1.1" 301 0
INFO <WSGIRequest: GET '/seminar2/'> request received
INFO "GET /seminar2/ HTTP/1.1" 200 17
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO "GET /seminar2/heads_tails/ HTTP/1.1" 200 32
INFO "GET / HTTP/1.1" 200 10
INFO <WSGIRequest: GET '/seminar2/heads_tails/?n=10'> request received
INFO "GET /seminar2/heads_tails/?n=10 HTTP/1.1" 200 32
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/users/'> request received
INFO <WSGIRequest: GET '/seminar2/users/'> request received
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/users/'> request received
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/users/'> request received
INFO <WSGIRequest: GET '/seminar2/users/'> request received
INFO <WSGIRequest: GET '/seminar2/users/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/users/'> request received
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/users/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/orders/'> request received
INFO E:\git\python\django_seminars\seminar2\urls.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/orders/'> request received
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/orders/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /seminar2/product/
INFO <WSGIRequest: GET '/seminar2/products/'> request received
INFO E:\git\python\django_seminars\seminar2\models.py changed, reloading.
INFO <WSGIRequest: GET '/seminar2/products/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar2/products/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar3/'> request received
INFO <WSGIRequest: GET '/seminar3/about/'> request received
ERROR Internal Server Error: /seminar3/about/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 39, in about
    return render(request, 'about.html', context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
INFO <WSGIRequest: GET '/seminar3/about/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /seminar3/homepage/
INFO <WSGIRequest: GET '/seminar3/home/'> request received
INFO E:\git\python\django_seminars\seminar3\views.py changed, reloading.
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/heads_tails/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/dice/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/20/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/20/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/20/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/20/'> request received!
INFO <WSGIRequest: GET '/seminar3/rand/20/'> request received!
INFO <WSGIRequest: GET '/seminar3/united/20/'> request received!
INFO <WSGIRequest: GET '/seminar3/united/10/'> request received!
INFO <WSGIRequest: GET '/seminar3/'> request received
INFO E:\git\python\django_seminars\seminar3\views.py changed, reloading.
INFO E:\git\python\django_seminars\seminar3\views.py changed, reloading.
WARNING Not Found: /favicon.ico
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 103, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__gt=days_ago).all()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1464, in get_prep_value
    return self.to_python(value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1420, in to_python
    parsed = parse_date(value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    return datetime.date.fromisoformat(value)
TypeError: fromisoformat: argument must be str
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 103, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__gt=days_ago).all()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1464, in get_prep_value
    return self.to_python(value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1430, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“365” value has an invalid date format. It must be in YYYY-MM-DD format.']
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 105, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__gt=datetime(0000, 00, days_ago)).all()
TypeError: 'str' object cannot be interpreted as an integer
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 105, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__gt=datetime(0000, 00, days_ago)).all()
ValueError: year 0 is out of range
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 100, in sorted_basket
    date = datetime.now() - datetime(0000, 00, days_ago)
ValueError: year 0 is out of range
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 100, in sorted_basket
    date = datetime.now() - datetime(0, 0, days_ago)
ValueError: year 0 is out of range
ERROR Internal Server Error: /seminar3/sorted_basket/3/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 100, in sorted_basket
    date = datetime.now() - datetime.date(days_ago)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\utils\datetime_safe.py", line 48, in date
    return date(self.year, self.month, self.day)
AttributeError: 'int' object has no attribute 'year'
INFO E:\git\python\django_seminars\seminar3\views.py changed, reloading.
INFO E:\git\python\django_seminars\seminar3\views.py changed, reloading.
INFO E:\git\python\django_seminars\seminar3\views.py changed, reloading.
ERROR Internal Server Error: /seminar3/sorted_basket/4/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 103, in sorted_basket
    before = today() - timedelta(days=days_ago)
TypeError: 'datetime.date' object is not callable
ERROR Internal Server Error: /seminar3/sorted_basket/4/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 105, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__date__range=(before, now)).all()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1305, in build_lookup
    lhs = self.try_transform(lhs, name)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1356, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'date' for DateField or join on the field not permitted.
ERROR Internal Server Error: /seminar3/sorted_basket/4/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 105, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__date__range=(before, now)).all()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1305, in build_lookup
    lhs = self.try_transform(lhs, name)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1356, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'date' for DateField or join on the field not permitted.
ERROR Internal Server Error: /seminar3/sorted_basket/4/365/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar3\views.py", line 105, in sorted_basket
    orders = Order.objects.filter(customer=user, date_ordered__date__range=(before, now)).all()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1305, in build_lookup
    lhs = self.try_transform(lhs, name)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\db\models\sql\query.py", line 1356, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'date' for DateField or join on the field not permitted.
WARNING Not Found: /seminar4/form5/
WARNING Not Found: /seminar4/form5/
WARNING Not Found: /favicon.ico
WARNING Not Found: /seminar4/form4/
INFO E:\git\python\django_seminars\seminar4\forms.py changed, reloading.
WARNING Not Found: /seminar4/form4/
WARNING Not Found: /seminar4/get_product1
WARNING Not Found: /seminar4/form5/1/
WARNING Not Found: /seminar4/form5/1/
INFO <WSGIRequest: GET '/seminar4/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
ERROR Internal Server Error: /seminar4/products/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar4\views.py", line 143, in products
    return render(request, 'catalog.html', {'products': products})
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: catalog.html
INFO <WSGIRequest: GET '/seminar4/products/'> request received
ERROR Internal Server Error: /seminar4/products/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar4\views.py", line 143, in products
    return render(request, 'catalog.html', {'products': products})
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: catalog.html
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/'> request received
INFO <WSGIRequest: GET '/seminar4/prod_edit/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/products/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /seminar4/product/1/product-1.jpg
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/prod_edit/'> request received
INFO <WSGIRequest: GET '/seminar4/prod_edit/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
INFO <WSGIRequest: GET '/seminar5/'> request received
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\admin.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /materials/
WARNING Not Found: /material/
WARNING Not Found: /material/accounts
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
WARNING Not Found: /material/accounts
WARNING Not Found: /favicon.ico
WARNING Not Found: /material/
WARNING Not Found: /materials/
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
ERROR Internal Server Error: /admin/logout/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar5\models.py changed, reloading.
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\views.py changed, reloading.
INFO E:\git\python\django_seminars\seminar5\views.py changed, reloading.
INFO E:\git\python\django_seminars\main\urls.py changed, reloading.
WARNING Not Found: /homepage/
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar5/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar5/'> request received
INFO <WSGIRequest: GET '/seminar5/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar5/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /seminar5//
INFO <WSGIRequest: GET '/seminar5/'> request received
INFO <WSGIRequest: GET '/seminar5/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar5/'> request received
INFO <WSGIRequest: GET '/seminar5/'> request received
INFO <WSGIRequest: GET '/seminar1/'> request received
INFO <WSGIRequest: GET '/seminar1/dice/'> request received!
INFO <WSGIRequest: GET '/seminar1/dice/'> request received!
INFO <WSGIRequest: GET '/seminar1/dice/'> request received!
INFO <WSGIRequest: GET '/seminar1/dice/'> request received!
INFO <WSGIRequest: GET '/seminar1/rand/'> request received
INFO <WSGIRequest: GET '/seminar1/rand/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar1/rand/'> request received
INFO <WSGIRequest: GET '/seminar1/rand/'> request received
WARNING Not Found: /render_panel/
WARNING Not Found: /1
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar1/rand/'> request received
INFO <WSGIRequest: GET '/seminar1/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
INFO <WSGIRequest: GET '/seminar2/heads_tails/'> request received
WARNING Not Found: /seminar3/heads_tails/
INFO <WSGIRequest: GET '/seminar3/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar3/'> request received
INFO <WSGIRequest: GET '/seminar3/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/products/'> request received
INFO <WSGIRequest: GET '/seminar4/'> request received
INFO <WSGIRequest: GET '/seminar4/'> request received
INFO <WSGIRequest: GET '/seminar3/'> request received
INFO <WSGIRequest: GET '/seminar4/'> request received
WARNING Not Found: /seminar4/dice/
WARNING Not Found: /seminar4/dice
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO <WSGIRequest: GET '/seminar5/'> request received
ERROR Internal Server Error: /seminar5/homepage/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\engine.py", line 212, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: material/includes/material_css.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar5\views.py", line 32, in home_page
    return render(request, 'home_page.html', {'form': form})
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: material/includes/material_css.html
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar4/'> request received
INFO <WSGIRequest: GET '/seminar6/'> request received
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO <WSGIRequest: GET '/seminar6/'> request received
ERROR Internal Server Error: /seminar6/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar6\views.py", line 12, in seminar6
    return render(request, 'seminar6.html')
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar6.html
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar6/'> request received
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar6/'> request received
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO <WSGIRequest: GET '/seminar6/'> request received
INFO E:\git\python\django_seminars\seminar6\views.py changed, reloading.
INFO E:\git\python\django_seminars\seminar6\views.py changed, reloading.
WARNING Not Found: /seminar6/total_in_db/
WARNING Not Found: /favicon.ico
ERROR Internal Server Error: /seminar6/total/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar6\views.py", line 22, in total_in_db
    'total': total[0]}
KeyError: 0
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar6\views.py changed, reloading.
ERROR Internal Server Error: /seminar6/view/
Traceback (most recent call last):
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\git\python\django_seminars\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\git\python\django_seminars\seminar6\views.py", line 31, in total_in_view
    'total': total['quantity__sum']}
TypeError: 'int' object is not subscriptable
INFO E:\git\python\django_seminars\seminar6\views.py changed, reloading.
WARNING Not Found: /favicon.ico
INFO E:\git\python\django_seminars\seminar6\views.py changed, reloading.
INFO E:\git\python\django_seminars\seminar6\models.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
INFO E:\git\python\django_seminars\main\settings.py changed, reloading.
